model_name: mstar_uncond_cnn
figure_path: ./results/Samples/ mstar_uncond_cnn

epochs: 1000
batch_size: 128
lr: 0.0001
loss: 1ser

clf:
  arch: cnn
  kernel_size: 5
  cond_dim: 48
  mod_ch: 80
  ch_mul: [1, 2, 3, 4]  # +1 niveau de downsampling
  num_res: 2         # plus de blocs résiduels par niveau
  emb_dim: 192
  dropout: 0.05
  
dataset: MSTAR
data_path: "data/MSTAR_hrrp.pkl"
split:
  val_size: 0.15
  test_size: 0.15
  stratified: true
  cv_folds: 5
  fold_index: 0
inf_mode: step
inf_every_n_step: 2000
inf_every_n_epoch: 1

conditionned:
  bool: 0
  cond_op: film # film or concat
